# Generated by Django 2.0.5 on 2018-05-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('pos1', models.CharField(max_length=40)),
                ('pos2', models.CharField(max_length=40)),
                ('pos3', models.CharField(max_length=40)),
                ('pos4', models.CharField(max_length=40)),
                ('pos5', models.CharField(max_length=40)),
                ('coach', models.CharField(max_length=40)),
            ],
        ),
    ]
