# Generated by Django 2.0.5 on 2018-05-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTS_teams', '0002_teams_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='achievements1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teams',
            name='achievements2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teams',
            name='achievements3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teams',
            name='achievements4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teams',
            name='logo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teams',
            name='previous_members',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teams',
            name='upcoming_events',
            field=models.TextField(default=''),
        ),
    ]
